-- Uruchom w HeidiSQL/mysql:
-- SHOW COLUMNS FROM aoferty;
--
-- Wszystkie kolumny:
SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA = 'locbd' AND TABLE_NAME = 'aoferty'
ORDER BY ORDINAL_POSITION;
--
-- Kolumny NOT NULL bez sensownego DEFAULT (wymagają wartości w INSERT):
-- SELECT COLUMN_NAME, COLUMN_TYPE, COLUMN_DEFAULT
-- FROM information_schema.COLUMNS
-- WHERE TABLE_SCHEMA = 'locbd' AND TABLE_NAME = 'aoferty'
--   AND IS_NULLABLE = 'NO' AND (COLUMN_DEFAULT IS NULL OR COLUMN_DEFAULT = '')
-- ORDER BY ORDINAL_POSITION;
